### PR TITLE
make mod parser public

### PR DESCRIPTION
**Pull request by gkorland**
ref #18 exposing the parsing results will allow us to use the ParseTokens to add new paths

### CODE REVIEW

**Comment by gkorland** [comment]
@freestrings can you please merge this PR? 
Based on this PR we can write a NodeVisitor and work around issue #18

**Comment by gkorland** [comment]
@freestrings

**Comment by freestrings** [comment]
@gkorland 
I have a lot of work these days, so I checked "mail" late.

The parser was developed for module internal use and plans to support joins and functions. this module is likely to change. there are no plans to make it public yet.

**Comment by gkorland** [comment]
@freestrings any other option you might expose this functionality?

**Comment by gkorland** [comment]
@freestrings that is only way I found to verify a path is `static` and can return at most one path

**Comment by ctron** [comment]
@freestrings @gkorland 

I would be interested in the same feature: see #61 #62 

As the PR is open for over a year now, with no progress and feedback, I am wondering if this crate is still maintained. I think it is ok, if it is not. But that would be good to know, so I might consider forking and re-publishing the crate myself.

**Comment by freestrings** [comment]
Fixed issue at https://github.com/freestrings/jsonpath/tree/feature/refactoring and will be merged soon.

**Pull request closed without merging**
