### PR TITLE
move lifetime to result

### PR DESCRIPTION
**Pull request by gkorland**
lifetime should be on the Vec<&'a Value> and not on the input

### CODE REVIEW

**Comment by gkorland** [comment]
@freestrings

**Comment by freestrings** [comment]
Sorry. I missed this pr notification. 
thanks!

**Comment by gkorland** [comment]
@freestrings thanks for merging!

**Comment by gkorland** [comment]
@freestrings any chance you release a new version with this fix?

**Comment by freestrings** [comment]
@gkorland, this fix will be released with #9.

**Comment by gkorland** [comment]
@freestrings great! when are you planing to release it?

**Comment by freestrings** [comment]
@gkorland in this month.

**Pull request merged**
