### PR TITLE
improve precompiled expression

### PR DESCRIPTION
**Pull request by ritchie46**
This PR adds `delete` and `replace_with` to a precompiled expression. Because the `Node`s are public, this is needed for me to don't pay the compilation price every time in a hot loop.

btw, a `cargo fmt`  reformatted all files. Is the formatting intentionally different? Otherwise I am happy to add a fmt commit to this PR.

### CODE REVIEW

**Comment by freestrings** [comment]
Thanks for PR. and please write unit tests.

**Comment by evgeniy-r** [comment]
Hello! 

We plan to use this library in [our project](https://github.com/datanymizer/datanymizer).
What is the situation with this PR?
I can write the required unit tests if needed.

**Comment by freestrings** [comment]
@evgeniy-r 

Yes. This PR was not merged because there were no unit tests.

But now in the master branch, `Compiled' is going to be deprecated. 
:  https://github.com/freestrings/jsonpath/blob/master/src/lib.rs#L567

This is because there was a change for performance improvement, but a release plan has not been released yet.

If you add unit tests, I will merge them. And I will move it to the new `PathCompiled` before release.

**Comment by ritchie46** [comment]
Sorry for the delay. I will close this as this will become deprecated.

**Pull request closed without merging**
